### ISSUE TITLE
fix github actions + add action for publishing to npm

### ISSUE THREAD

**Issue by LironHazan** [TypeStrong/ts-mockito#19]

**Comment by LironHazan** [comment]
@cspotcode I don't have the settings tab on this repo,
can you add a secrete config so we can setup the action which bumps up a version and publish to npm on merge to master?

**Comment by LironHazan** [comment]
@cspotcode BTW I'm on a maternity leave till October, working on side projects so if you'll need a hand with other open source stuff I'll be happy to join ❇️

**Comment by cspotcode** [comment]
Oh nice, you're lucky to have the time away from work for side projects.  There is always work to be done on ts-node if that's your cup of tea.  And I have some other projects that need to be polished and published that might be more fun.  I'll think about it.

Let me see if I can grant you the settings tab.  I'm not sure if it's hidden due to permissions, or hidden because this is a fork.

**Comment by cspotcode** [comment]
I've requested access; should hopefully have it soon.  Then I'll give you full ownership of this repo to configure the changes, since I'm not 100% sure what they'll entail.  FWIW there are various 2FA requirements on npmjs.com; they may need to be configured, too.

**Comment by LironHazan** [comment]
> Oh nice, you're lucky to have the time away from work for side projects. There is always stuff to be done on ts-node if that's your cup of tea. And I have some other projects that need to be polished and published that might be more fun. I'll think about it.
> 
Thanks :) I'll take a look at the current ts-node issues.

**Comment by cspotcode** [comment]
@LironHazan you are now an "Admin" for this repository, so you should have full access to configure Github Actions.

**Comment by LironHazan** [comment]
@cspotcode great thanks! I see the settings tab

**Comment by LironHazan** [comment]
sure
